// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKOdzipDvmWHLt6YcYdw5SMNoFNICJc1s',
    appId: '1:597164812529:web:4b28e351f718234c362150',
    messagingSenderId: '597164812529',
    projectId: 'lemme-in-db6e1',
    authDomain: 'lemme-in-db6e1.firebaseapp.com',
    storageBucket: 'lemme-in-db6e1.appspot.com',
    measurementId: 'G-NZH46QBG09',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGE03UKRvnwaLsz4peGYRJVBs1MXEX-Ts',
    appId: '1:597164812529:android:7bd76c48ec1b8952362150',
    messagingSenderId: '597164812529',
    projectId: 'lemme-in-db6e1',
    storageBucket: 'lemme-in-db6e1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4sbDrXpIXX0dj4UuidaaSSnYUYXx6yQc',
    appId: '1:597164812529:ios:afa08059fa200c52362150',
    messagingSenderId: '597164812529',
    projectId: 'lemme-in-db6e1',
    storageBucket: 'lemme-in-db6e1.appspot.com',
    iosBundleId: 'com.example.lemmeInProfofconc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4sbDrXpIXX0dj4UuidaaSSnYUYXx6yQc',
    appId: '1:597164812529:ios:ec9c53dc00317b58362150',
    messagingSenderId: '597164812529',
    projectId: 'lemme-in-db6e1',
    storageBucket: 'lemme-in-db6e1.appspot.com',
    iosBundleId: 'com.example.lemmeInProfofconc.RunnerTests',
  );
}
